# =========================================================
# UI Service (External Access)
# =========================================================
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: retail-store
  labels:
    app: ui
spec:
  type: LoadBalancer
  selector:
    app: ui
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
# =========================================================
# UI Deployment
# =========================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: retail-store
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: us-central1-docker.pkg.dev/solid-study-480405-c3/retail-shop/ui:a785cf0
          ports:
            - containerPort: 8080

          env:
            - name: CATALOG_SERVICE_URL
              value: http://catalog:8080
            - name: CART_SERVICE_URL
              value: http://cart:8080
            - name: CHECKOUT_SERVICE_URL
              value: http://checkout:8080
            - name: ORDERS_SERVICE_URL
              value: http://orders:8080

          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
