# =========================================================
# Cart Service
# Uses DynamoDB Local (in-cluster)
# =========================================================

apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: retail-store
  labels:
    app: cart
spec:
  selector:
    app: cart
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: retail-store
  labels:
    app: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:

      # Wait for DynamoDB Local to respond
      initContainers:
        - name: wait-for-dynamodb
          image: curlimages/curl:8.11.1
          command:
            - sh
            - -c
            - |
              until curl -s http://carts-db:8000; do
                echo "Waiting for DynamoDB...";
                sleep 3;
              done

      containers:
        - name: cart

          # GCP Artifact Registry image with immutable tag
          image: us-central1-docker.pkg.dev/solid-study-480405-c3/retail-shop/cart:a785cf0

          ports:
            - containerPort: 8080

          env:
            - name: SERVER_TOMCAT_ACCESSLOG_ENABLED
              value: "true"

            # -----------------------------
            # DynamoDB Local configuration
            # -----------------------------
            - name: RETAIL_CART_PERSISTENCE_PROVIDER
              value: dynamodb
            - name: RETAIL_CART_PERSISTENCE_DYNAMODB_ENDPOINT
              value: http://carts-db:8000
            - name: RETAIL_CART_PERSISTENCE_DYNAMODB_CREATE_TABLE
              value: "true"

            # Dummy credentials required by SDK
            - name: AWS_ACCESS_KEY_ID
              value: dummy
            - name: AWS_SECRET_ACCESS_KEY
              value: dummy

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
