apiVersion: v1
kind: Service
metadata:
  name: carts-db
  namespace: retail-store
  labels:
    app: carts-db
spec:
  selector:
    app: carts-db
  ports:
    - name: http
      port: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts-db
  namespace: retail-store
  labels:
    app: carts-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carts-db
  template:
    metadata:
      labels:
        app: carts-db
    spec:
      containers:
        - name: dynamodb-local
          image: amazon/dynamodb-local:1.20.0
          ports:
            - containerPort: 8000
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
