# -----------------------------
# Service for Catalog API
# -----------------------------
apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: retail-store
  labels:
    app: catalog
spec:
  selector:
    app: catalog
  ports:
    - port: 8080
      targetPort: 8080
---
# -----------------------------
# Deployment for Catalog Service
# -----------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: retail-store
  labels:
    app: catalog
spec:
  replicas: 1   # Can be scaled later with HPA
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      # Init container ensures DB is reachable before app starts
      initContainers:
        - name: wait-for-mariadb
          image: mariadb:10.9
          command:
            - sh
            - -c
            - |
              until mysqladmin ping \
                -h catalog-db \
                -u catalog_user \
                -p$DB_PASSWORD \
                --silent; do
                echo "Waiting for MariaDB...";
                sleep 5;
              done
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MYSQL_PASSWORD

      containers:
        - name: catalog
          # Artifact Registry image with immutable tag
          image: us-central1-docker.pkg.dev/solid-study-480405-c3/retail-shop/catalog:a785cf0

          ports:
            - containerPort: 8080

          env:
            - name: GIN_MODE
              value: "release"
            - name: RETAIL_CATALOG_PERSISTENCE_PROVIDER
              value: mysql
            - name: RETAIL_CATALOG_PERSISTENCE_ENDPOINT
              value: catalog-db:3306
            - name: RETAIL_CATALOG_PERSISTENCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MYSQL_PASSWORD

          # Traffic allowed only after app is ready
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10

          # Restart container if app becomes unhealthy
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
