apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-databases
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Darshan9154/polyglot-shop-gitops.git
    targetRevision: main
    path: infra/databases
  destination:
    server: https://kubernetes.default.svc
    namespace: retail-store
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
