apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-messaging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Darshan9154/polyglot-shop-gitops.git
    targetRevision: main
    path: infra/messaging
  destination:
    server: https://kubernetes.default.svc
    namespace: retail-store
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
