apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-store-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Darshan9154/polyglot-shop-gitops.git
    targetRevision: main
    path: environments/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
